### ISSUE TITLE
Incompatibility problem

### ISSUE THREAD

**Issue by Reimix** [TheCreeperOfRedstone/RPG-Items-2#12]
Craftbukkit Version : 1.7.2-R0.3
Build number: 2987

The plugin RpgItems2 have a compatibility problem with GemManager 1.5.1, im not a expert, but look like they will try override each other.

The error:
[18:39:24 ERROR]: Could not load 'plugins\GemManager.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPlug
inLoader.java:184) ~[Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks
]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:133) [Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugins(CraftServer.ja
va:257) [Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.<init>(CraftServer.java:23
5) [Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks]
        at net.minecraft.server.v1_7_R1.PlayerList.<init>(PlayerList.java:63) [C
raftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks]
        at net.minecraft.server.v1_7_R1.DedicatedPlayerList.<init>(SourceFile:14
) [Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks]
        at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.jav
a:126) [Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java
:424) [Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:6
17) [Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_51]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.7.0_51]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.7.0_51]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.7.0_51]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.7.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPlug
inLoader.java:172) ~[Craftbukkit.jar:git-Bukkit-1.7.2-R0.2-10-gd51ccd1-b2987jnks
]
        ... 8 more
[18:39:24 INFO]: [RPG Items] Loading RPG Items v3.0.4
[18:39:24 WARN]: ***\* SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[18:39:24 WARN]: The server will make no attempt to authenticate usernames. Bewa
re.
[18:39:24 WARN]: While this makes the game possible to play without internet acc
ess, it also opens up the ability for hackers to connect with any username they
choose.
[18:39:24 WARN]: To change this, set "online-mode" to "true" in the server.prope
rties file.
[18:39:24 INFO]: Preparing level "world"
[18:39:24 INFO]: Preparing start region for level 0 (Seed: 3559308679012256363)
[18:39:25 INFO]: Preparing spawn area: 92%
[18:39:25 INFO]: ----- Bukkit Auto Updater -----
[18:39:25 INFO]: It appears that you're running a Development Build, when you've
 specified in bukkit.yml that you prefer to run Recommended Builds.
[18:39:25 INFO]: If you would like to be kept informed about new Development Bui
ld releases, it is recommended that you change 'preferred-channel' in your bukki
t.yml to 'dev'.
[18:39:25 INFO]: With that set, you will be told whenever a new version is avail
able for download, so that you can always keep up to date and secure with the la
test fixes.
[18:39:25 INFO]: If you would like to disable this warning, simply set 'suggest-
channels' to false in bukkit.yml.
[18:39:25 INFO]: ----- ------------------- -----
[18:39:25 INFO]: Preparing start region for level 1 (Seed: 3559308679012256363)
[18:39:26 INFO](Done): [RPG Items] Enabling RPG Items v3.0.4
[18:39:26 INFO](Done): Server permissions file permissions.yml is empty, ignoring it

Using Rpg items 1, working well, definitively something is wrong.

**Comment by michalet** [comment]
I'm no expert either, but it seems that GemManager has invalid plugin.yml, so bukkit can't load it. Can't see any errors concerning RPG Items, just bukkit offline mode warning.

**Comment by Reimix** [comment]
The error dont was with Rpgitems 2, but was before, because of that, i thinked that the plugins was overriding each other, the error is with some random plugin or Rpgitems2.
RpgItems2 (when is not another plugin) shows "Invalid plugin description in plugin.yml".
I removed gem manager for other plugins, but Rpgitems2 still acts awkward, i will stick with Rpgitems 1.
